module.exports = {
  dateOfEarliestKnownCreditAccount: 'Date of Earliest known Credit Account',
  previousEnquiries: 'Previous Enquiries',
  accounts: 'Accounts',
  defaults: 'Defaults',
  bankruptcyProceedings: 'Bankruptcy Proceedings',
  securedCreditLimit: 'Secured Credit Limit',
  unsecuredCreditLimit: 'Unsecured Credit Limit',
  exemptedCreditLimit: 'Exempted Credit Limit',
  debtManagementProgramme: 'Debt Management Programme',
  idTheft: 'ID Theft',
  _12_BTI: '12 x BTI',
  surname: 'Surname',
  firstName: 'First Name',
  secondName: 'Second Name',
  foreNames: 'Fore Names',
  unformattedName: 'Unformatted Name',
  idType: 'ID Type',
  idNumber: 'ID Number',
  dateOfBirth: 'Date of Birth',
  gender: 'Gender',
  nationality: 'Nationality',
  maritalStatus: 'Marital Status',
  postalCode: 'Postal Code',
  dateLoaded: 'Date Loaded',
  name: 'Name',
  occupation: 'Occupation',
  employer: 'Employer',
  productType: 'Product Type',
  grantorBank: 'Grantor Bank',
  accountType: 'Account Type',
  dateOpenClose: 'Date Open / Close',
  openedDate: 'Opened Date',
  closedDate: 'Closed Date',
  overdueBalance: 'Overdue Balance',
  cf: 'Last 12 cycles Cash Advance / Bal. Transfer Full Payment',
  cashAdvance: 'Cash Advance',
  fullPayment: 'Full Payment',
  enquiryType: 'Enquiry Type',
  date: 'Date',
  client: 'Client',
  originalAmt: 'Original Amt at load Date',
  balance: 'Balance',
  status: 'Status',
  statusDate: 'Status Date',
  bankruptcyNumber: 'Bankruptcy Number',
  orderDate: 'Order Date',
  petitionDate: 'Petition Date',
  originalOrderDate: 'Original Order Date',
  gazetteDate: 'Gazette Date',
  orderNature: 'Nature of Order',
  drsCaseNumber: 'DRS Case Number',
  commencementDate: 'Commencement Date',
  completionDate: 'Completion Date',
  failureDate: 'Failure Date',
  sourceCard: 'Source Card',
  source: 'Source',
  riskGrade: 'Risk Grade',
  riskGradeDescription: 'Risk Grade Description',
  probabilityOfDefault: 'Probability of Default',
  riskOdds: 'Risk Odds',
  immatureCreditHistory: 'Immature Credit History',
  creditExposure: 'Credit Exposure',
  delinquencyPresence: 'Delinquency Presence',
  notEnoughCleanHistory: 'Not Enough Clean History',
  adverseCreditHistory: 'Adverse Credit History',
  tooManyEnquiries: 'Too Many Enquiries',
  type: 'Type',
  texts: 'Text',
  litigationWrits: 'Litigation Writs',
  bankruptcyPetitions: 'Bankruptcy Petitions',
  defendantName: 'Defendant Name',
  courtCode: 'Court Code',
  caseNumber: 'Case Number',
  dateFiled: 'Date Filed',
  natureOfClaim: 'Nature of Claim',
  claimCurrency: 'Claim Currency',
  claimAmount: 'ClaimAmount',
  plaintiffNames: 'Plaintiff Names',
  securedBalances: 'Secured Balances',
  unsecuredInterestBearingBalances: 'Unsecured Interest Bearing Balances',
  unsecuredNonInterestBearingBalances: 'Unsecured NonInterest Bearing Balances',
  exemptedBalances: 'Exempted Balances',
  clientId: 'Client Id',
  userId: 'User Id',
  runNo: 'Run No',
}
